name: Remove waiting label from PRs

on:
  pull_request_target:
    types: synchronize

jobs:
  delabel:
    name: Remove label
    runs-on: ubuntu-latest

    steps:
      - name: Remove label
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const [owner, repo] = context.payload.repository.full_name.split('/');
            await github.rest.issues.removeLabel({
              owner: owner,
              repo: repo,
              issue_number: context.payload.number,
              name: "Status: Waiting on Author",
            });
